apiVersion: v1
kind: Service
metadata:
  name: ai-code-generator-service
spec:
  type: NodePort
  selector:
    app: ai-code-generator
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
